### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by dperny** [docker/docker-e2e#50]
Right now maintainers with write access to this project are me, @dhiltgen, @dongluochen, and @AntaresS. The project would move faster without any loss of quality if we had a couple of more people who could review and LGTM changes, esp. because everyone is a little swamped until after DockerCon.

Feel free to nominate others or yourselves.

**Comment by vdemeester** [comment]
@dperny I am definitely interested 👼 😉

**Comment by dperny** [comment]
Added @vikstrous @sanimej @davidwilliamson and @vdemeester.

Thank you and I'm sorry.

**Comment by dperny** [comment]
Added @ry4nz
