### ISSUE TITLE
Make rhel7.3 working with MAC virtualbox machine

### ISSUE THREAD

**Issue by ry4nz** [docker/docker-e2e#65]
`VBOX_OS_LINUX=rhel7.3` has some network issues at the memont.

**Comment by ry4nz** [comment]
looks like it can just be resolved by adding the following to the base image.
```
cat /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
BOOTPROTO=dhcp
ONBOOT=yes
```

**Comment by dhiltgen** [comment]
I think we can close this now with the updated base images.
